## **General**
1- What's the difference between a Machine Learning (ML) Model and a Machine Learning algorithm.

2- Why we need to study Linear Algebra for ML?

# Responses:
1- model is some algorithms that found a solution to a problem

2- in LA we have operation needed to make our operation with mlatrix and vectors etc 

**## Vectors:**

**1- create a vector: **

Our vector can be written as v=(2,1), but more formally we would use the following notation, in which the dimensional coordinate values for the vector are shown as a matrix:$$\vec{v} = \begin{bmatrix}2 \\ 1 \end{bmatrix}$$

In [3]:
import numpy as np
#TO DO...
#v=np.array([2, 1]) #horizontally 
v=np.array([[2],[1]]) #vertically
print(v)

[[2]
 [1]]


### **2-Calculating Magnitude**

In [5]:
import math
#TO DO... 
m= math.sqrt(sum(x**2 for x in v))
print(m)

2.23606797749979



**3- Vector Addition:**
So far, we've worked with one vector at a time. What happens when you need to add two vectors.

Let's take a look at an example, we already have a vector named v, as defined here:$$\vec{v} = \begin{bmatrix}2 \\ 1 \end{bmatrix}$$Now let's create a second vector, and called s like this:$$\vec{s} = \begin{bmatrix}-3 \\ 2 \end{bmatrix}$$

And we have :$$\vec{z} = \vec{v}+\vec{s}$$

In [6]:

import math
import numpy as np

v = np.array([[2],[1]])
s = np.array([[-3],[2]])
z = v+s
print (z)

[[-1]
 [ 3]]



4- Dot Product Multiplication


$$ \vec{d}=\vec{v} \cdot \vec{s} = (v_{1} \cdot s_{1}) + (v_{2} \cdot s_{2}) ... + \; (v_{n} \cdot s_{n})$$

In [8]:

import math
import numpy as np

d=0
for i in range(len(v)):
  d+= v[i]*s[i]
print (d)

[-4]


## **Matrices:**

# 1- create a Matrice:
A matrix arranges numbers into rows and columns, like this:

$$A = \begin{bmatrix}
  1 &amp; 2 &amp; 3 \\
  4 &amp; 5 &amp; 6
 \end{bmatrix}
$$

In [13]:
import numpy as np

A = np.array([[1, 2, 3],[4, 5, 6] ])
print (A)

[[1 2 3]
 [4 5 6]]



#2- Matrix Transposition
You can transpose a matrix, that is switch the orientation of its rows and columns. You indicate this with a superscript T, like this:

$$\begin{bmatrix}1 &amp; 2 &amp; 3 \\4 &amp; 5 &amp; 6\end{bmatrix}^{T} = \begin{bmatrix}1 &amp; 42 &amp; 53 &amp; 6 \end{bmatrix}$$

a- How can we do it mathematically? 

lines became colons and colons became lignes



b- with Python: 

In [14]:
import numpy as np

AT= A.T
print(AT)

[[1 4]
 [2 5]
 [3 6]]


## **Eigendecomposition:**

So we've learned a little about eigenvalues and eigenvectors; but you may be wondering what use they are. Well, one use for them is to help decompose transformation matrices.

1- How can we decompose a matrix? ( Rules and steps)
2- (Bonus) Do it in python with your exampls.


1- into factors using identity matrix multiplied by lambda 

In [17]:
#2 bonus
import numpy as np
M = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9] ])
e_values , e_vectors =np.linalg.eig(M)
print(e_values)
print(e_vectors)

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
